[package]
name = "mylang"
version = "0.1.0"
authors = ["Peter Delevoryas <me@peterd.net>"]
edition = "2018"

[[bin]]
name = "mylangc"
path = "src/main.rs"

[dependencies.llvm-sys]
git = "https://github.com/peterdelevoryas/llvm-sys"

[dev-dependencies]
filecheck = "0.4.0"
