[package]
name = "r2"
version = "0.1.0"
authors = ["Peter Delevoryas <me@peterdelevoryas.com>"]
edition = "2018"

[dependencies.llvm-sys]
git = "http://github.com/peterdelevoryas/llvm-sys.git"

[dev-dependencies]
filecheck = "0.4.0"
